REPO_OWNER ?= temporal-sa
REPO_NAME ?= hackathon-starter

TEMPLATES_DIR = templates
README = README.md
TEMPORAL_PID := $(shell pgrep -f "temporal server start-dev" | head -n 1)

generate-readme:
	@echo "Copy readme template"
	@cp ${TEMPLATES_DIR}/${README}.tpl ${README}

	@echo "Set owner/name for repositories"
	@sed -i "s#__OWNER__#${REPO_OWNER}#g; s#__REPO__#${REPO_NAME}#g" ${README}

# Follow the markdown-toc pre-commit hook, but use the node CLI for speed
# @link https://github.com/trussworks/pre-commit-hooks/blob/942b38145556f34d20fe6a0784f5735f6861e4b5/pre-commit-markdown-toc
	@echo "Generating table of contents"
	@bash -c "npx --yes markdown-toc --bullets='*' --append=$$'\n\n<!-- Regenerate with \"pre-commit run -a markdown-toc\" -->' -i \"$(README)\""
	@sed -i '1i<!-- This file is autogenerated - make changes in ${TEMPLATES_DIR}/${README}.tpl -->' ${README}
.PHONY: generate-readme

temporal:
	@temporal server start-dev --ip=0.0.0.0
.PHONY: temporal

temporal-stop:
	@if [ -n "$(TEMPORAL_PID)" ]; then \
		kill $(TEMPORAL_PID) || true; \
	fi
	@echo "Restart Temporal by running \"make temporal\""
.PHONY: temporal-stop
